### ISSUE TITLE
Another option for running conda in CI

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/python-intermediate-development#38]
Logging this here before I forget - I've just had to get conda running in GitHub Actions for a hobby project

---

I managed to get a conda environment working with this action: https://github.com/marketplace/actions/setup-miniconda
and the yml config below. Note that this is on a self-hosted runner as it's currently a private repo - you shouldn't need the `runs-on` tag or the manual `$CONDA` environment variable on one of GitHub's CI runners.

```
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      fail-fast: false

      matrix: 
        python-version: ["3.8"]

    runs-on: [self-hosted]

    defaults:
      run:
        shell: bash -l {0}

    env:
      CONDA: /home/actions-runner/miniconda3

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: autocg
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Check conda
      run: |
        conda info
        conda list

    - name: Run tests
      run: |
        python -m pytest
```
